---
apiVersion: v1
kind: Service
metadata:
  name: braulio1-test-redis-service
  labels:
    username: braulio1
    env: test
spec:
  type: ClusterIP
  selector:
    app: braulio1-test-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
