---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: braulio1-test-redis-deployment
  labels:
    username: braulio1
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: braulio1-test-redis
  template:
    metadata:
      labels:
        app: braulio1-test-redis
    spec:
      containers:
        - name: redis
          imagePullPolicy: Always
          image: redis:7
          ports:
          - name: FLASK_APP
            value: "gene_api.py"
          ports:
          - name: http
            containerPort: 6379
          volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
        - name:  redis-data
          persistentVolumeClaim:
            claimName:  braulio1-test-redis-pvc
