---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-deployment
  labels:
    username: braulio1
    env: test
    app: braulio1-test-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: braulio1-test-flask
  template:
    metadata:
      labels:
        app: braulio1-test-flask
        username: braulio1
        env: test
    spec:
      containers:
        - name: flask-container
          imagePullPolicy: Always
          image: brauliolpx/gene_api:hw07
          ports:
          - name: flask
            containerPort: 5000
