---
apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
  labels:
    username: braulio1
    env: test
spec:
  type: ClusterIP
  selector:
    app: flasktestapp
  ports:
  - name: flask
    port: 5000
    targetPort: 5000
