---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-test-deployment
  labels:
    username: braulio1
    env: test
    app: redistestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redistestapp
  template:
    metadata:
      labels:
        app: redistestapp
        username: braulio1
        env: test
    spec:
      containers:
        - name: redis-container
          imagePullPolicy: Always
          image: redis:7
          volumeMounts:
          - name: redis-data-pvc
            mountPath: "/data"
          ports:
          - name: redis
            containerPort: 6379
      volumes:
      - name: redis-data-pvc
        persistentVolumeClaim:
          claimName: redis-data-pvc   
